#pragma once
#include "redis_common.hpp"

// redis db
static const sql_table all_db_table[] =
{
	{ "role", false, "rk=%lu", NULL },
	{ "role_ex", false, "rk=%lu", NULL },
	{ "role_money", false, "rk=%lu", NULL },
	{ "role_fight", false, "rk=%lu", NULL },
	{ "role_tower", false, "rk=%lu", NULL },
	{ "country_bounty", false, "rk=%lu", NULL },
	{ "expedition", false, "rk=%lu", NULL },
	{ "item", false, "role_uid=%lu", "role_uid" },
	{ "task", false, "rk=%lu", NULL },
	{ "heroes", false, "role_uid=%lu", "role_uid" },
	{ "role_mount", false, "role_uid=%lu", "role_uid" },
	{ "role_trade_item", false, "role_uid=%lu", "role_uid" },
	{ "arena_role_data", false, "rk=%lu", NULL },
	{ "achieve", false, "rk=%lu", NULL },
	{ "role_dungeon", false, "role_uid=%lu", "role_uid" },
	{ "role_dungeon_times", false, "rk=%lu", NULL },
	{ "active_reward", false, "rk=%lu", NULL },
	{ "random_shop", false, "role_uid=%lu", "role_uid" },
	{ "liandan", false, "rk=%lu", NULL },
	{ "family_skill", false, "rk=%lu", NULL },
	{ "activity", false, "rk=%lu", NULL },
	{ "equip_plan", false, "rk=%lu", NULL },
	{ "patrol_hire", false, "rk=%lu", NULL },
	{ "luckydraw", false, "rk=%lu", NULL },
	{ "business_act", false, "rk=%lu", NULL },
	{ "recharge", false, "rk=%lu", NULL },
	{ "office", false, "rk=%lu", NULL },

	{ "global_user", true, NULL, "name:did" },
	{ "global_server_data", true, NULL, NULL },
	{ "city", true, NULL, NULL },
	{ "country", true, NULL, NULL },
	{ "country_office", true, NULL, "country_id" },
	{ "family", true, NULL, "name" },
	{ "family_member", true, "family_id<>0", "family_id" },
	{ "family_build", true, NULL, "id" },
	{ "family_war", true, NULL, "week" },
	{ "item_limit", true, NULL, NULL },
	{ "friend", true, NULL, "role_uid" },
	{ "friend_related", true, NULL, NULL },
	{ "mail", false, "to_uid=%lu", "to_uid" },
	{ "global_mail", true, NULL, NULL },
	{ "shop_goods", true, NULL, NULL },
	{ "user_goods", true, NULL, "role_uid" },
	{ "king_war_apply", true, NULL, "king_war_id" },
	{ "levelsort", true, NULL, NULL },
	{ "towersort", true, NULL, NULL },
	{ "criminalsort", true, NULL, NULL },
	{ "achievesort", true, NULL, NULL },
	{ "familysort", true, NULL, NULL },
	{ "goods", true, NULL, NULL },
	{ "general_info", true, NULL, NULL },
	{ "goods_care", true, NULL, NULL },
	{ "rarity_price", true, NULL, NULL },
	{ "arena_fight_data", true, NULL, NULL },
	{ "offline_role_data", true, NULL, NULL },
	{ "redbag", true, NULL, NULL },
	{ "role_simple_data", true, NULL, NULL },
	{ "offline_arena", true, NULL, NULL },
	{ "challenge", true, NULL, "challenger_uid:target_uid:challenge_time" },
	{ "general_status", true, NULL, NULL },
	{ "general_target_first_name", true, NULL, NULL },
	{ "charmsort", true, NULL, NULL },
	{ "recruitsort", true, NULL, NULL },
	{ "coppersort", true, NULL, NULL },
	{ "goldsort", true, NULL, NULL },
	{ "powersort", true, NULL, NULL },
	{ NULL, false, NULL, NULL }
};